### PR TITLE
Fix aspect ratio landscape

### PR DESCRIPTION
**Pull request by CapitainOats**
Fix for issue https://github.com/googlesamples/android-ConstraintLayoutExamples/issues/32

### CODE REVIEW

**Comment by CapitainOats** [comment]
I signed it!

**Comment by CapitainOats** [comment]
I signed it!

**Comment by CapitainOats** [comment]
@thagikura please can you have a look on this change. :)

**Comment by thagikura** [comment]
Apologies for the delay..
Thanks for the PR. LGTM.

**Pull request merged**
